dist: xenial
language: python
python:
  - "2.7.13"
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"
install:
  - pip install pylint six pyyaml paramiko
script:
  - pylint --py3k --disable=W1633,W1648,W1662 ccmlib
  - pylint --disable=all --enable=E,F ccmlib
  - nosetests
jdk:
  - openjdk11
env:
  - CASSANDRA_USE_JDK11=true
addons:
  apt:
    packages:
      - ant
      - ant-optional