language: python
python:
  - "2.7.18"
  - "3.6.15"
  - "3.7.12"
  - "3.8.12"
  - "3.9.9"
  - "3.10.1"
install:
  - pip install pylint six pyyaml paramiko psutil
script:
  - pylint --py3k --disable=W1633,W1648,W1662 ccmlib
  - pylint --disable=all --enable=E,F ccmlib
  - nosetests
jdk:
  - openjdk11
env:
  - CASSANDRA_USE_JDK11=true
addons:
  apt:
    packages:
      - ant
      - ant-optional
