name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -r tests/requirements.txt

      - name: Run linter
        run: pylint --output-format msvs --reports y ccmlib || true

      - name: Run linter for tests
        run: pylint --output-format msvs --reports y tests || true

      - name: Run tests
        run: |
          pytest --junitxml=junit.xml tests

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'junit.xml'
          annotate_only: true
